### ISSUE TITLE
Exceptions logging

### ISSUE THREAD

**Issue by krioo** [mediamonks/php-rest-api#1]
One thing I am missing is the possibility to log exceptions, as Symfony is doing it by default in ExceptionListener: https://github.com/symfony/http-kernel/blob/master/EventListener/ExceptionListener.php#L45

Since the RestApiEventSubscriber subscribes to the kernel.exception with a priority of 512, the ExceptionListener is never reached to lot the errors, but the RestApiEventSubscriber does not log the errors either.

**Comment by slootjes** [comment]
You could extend the exception listener to implement a logger or create a separate listener with a higher priority where you can log them.

**Comment by krioo** [comment]
Thank you for a quick answer, @slootjes :) The case is that right now, for all API endpoints which use the php-rest-api, no errors are logged at all - even those which Symfony logs automatically by default as Uncaught PHP Exceptions.

Is the error logging suppressed on purpose? Is the suggested strategy to log errors always before the RestApiEventSubscriber handles the response?

**Comment by slootjes** [comment]
Error logging isn't suppressed on purpose but it's really important that generating a correct output is generated before any other handler will usually do that. If I would want to log errors myself the strategy would indeed be to have another subscriber which is triggered before this one is.

**Comment by krioo** [comment]
I understand why it needs to happen as an early event, but it also means no other listeners will be triggered.

Would it make sense to add a default Uncaught exception logger as Symfony does it by default? Or is this completely out of scope from your point of view and there should be a custom ErrorHandler registered?

**Comment by mediamonks-robert** [comment]
I don't think this is the responsibility of the bundle, you should handle that sort of things in your own handlers/subscribers.

**Comment by krioo** [comment]
OK, I understand.

Maybe it would be a good idea to mention it in the documentation, because in case somebody just enables the bundle for all his routes, no errors will be ever logged the way Symfony does that by default and that is a bit unclear.

**Comment by mediamonks-robert** [comment]
Good suggestion, will look into this.

**Comment by krioo** [comment]
Awesome stuff, thanks a lot!

**Comment by Edwin-Luijten** [comment]
Closing this due to it being as old as dinosaurs.

**Comment by krioo** [comment]
Aww 🥲
