### ISSUE TITLE
plans for PHP 8?

### ISSUE THREAD

**Issue by csizmazia** [mediamonks/php-rest-api#5]
hey!
are there any plans to allow this package to be used on PHP 8?
not talking about using any PHP 8 features or so. allowing it in `composer.json` would already be a start

**Comment by slootjes** [comment]
Hi cszismazia! Good idea :) Feel free to submit a PR to speed things up.

**Comment by csizmazia** [comment]
in the meantime i also created my own PR, which solely focuses on making PHP 8 possible:
https://github.com/mediamonks/php-rest-api/pull/7

could you please give it a look and merge it eventually? thank you!

**Comment by slootjes** [comment]
It's merged. Thanks for your patience and your support.

**Comment by csizmazia** [comment]
yay, thank you! :)

**Comment by csizmazia** [comment]
now i have to bother you again, though...
i saw that you merged to master but did not release a new version. also, https://github.com/mediamonks/symfony-rest-api-bundle did not receive an update or new release.
do you have resources to do so?

**Comment by Edwin-Luijten** [comment]
Just created at tag `2.2.0`.

**Comment by csizmazia** [comment]
that's a great first step, thank you! :)
would you mind looking into the bundle as well? i just created a PR for it: https://github.com/mediamonks/symfony-rest-api-bundle/pull/20

**Comment by csizmazia** [comment]
@Edwin-Luijten sorry to bother you again...
something messed up my previous change, see https://github.com/mediamonks/php-rest-api/pull/8
